inputs_def:
  - handle: input_table
    description: "%nl-to-pandas-input-table%"
    json_schema:
      type: object
      properties:
        columns:
          type: array
        rows:
          type: array
        schema:
          type: object
    nullable: false

  - handle: instruction
    description: "%nl-to-pandas-instruction%"
    json_schema:
      type: string
      ui:widget: text
    nullable: false

  - handle: llm
    description: "%nl-to-pandas-llm%"
    json_schema:
      ui:widget: llm::model
    value:
      model: oomol-chat
      temperature: 0.5
      top_p: 1
      max_tokens: 128000
    nullable: false

outputs_def:
  - handle: python_code
    json_schema:
      type: string
    description: "%nl-to-pandas-python-code%"

  - handle: result_table
    json_schema:
      type: object
      properties:
        columns:
          type: array
        rows:
          type: array
        schema:
          type: object
    description: "%nl-to-pandas-result-table%"

  - handle: execution_logs
    json_schema:
      type: string
    description: "%nl-to-pandas-execution-logs%"

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "%nl-to-pandas-title%"
icon: ":carbon:function:"
description: "%nl-to-pandas-description%"
